encoding:         utf-8
lang:             zh-cn

# Information
title:            R66037
url:              https://wzjistc.github.io
baseurl:          /R66037

assets:
  styles:         /assets/styles
  fonts:          /assets/fonts
  scripts:        /assets/scripts
  images:         /assets/images
